name: Build

# on: [push, pull_request]

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build-platformio:
    runs-on: ubuntu-latest
    name: Build Marlin
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install PlatformIO
        run: |
          pip install --upgrade pip
          pip install platformio
      - name: Run PlatformIO
        run: python -m platformio run